### ISSUE TITLE
FileNotFoundError: Could not find module 'libtxchacha.dll' (or one of its dependencies). Try using the full path with constructor syntax.

### ISSUE THREAD

**Issue by 421634065** [Tontonnow/ddddhmtx#1]
FileNotFoundError: Could not find module 'libtxchacha.dll' (or one of its dependencies). Try using the full path with constructor syntax.
一直爆这个错误

**Comment by Tontonnow** [comment]
需要安装gcc配置环境变量 ，传了一个clang编译可以直接用

**Comment by 421634065** [comment]
还是不行 我试试安装gcc 环境变量

**Comment by 421634065** [comment]
还是不行  一直报错FileNotFoundError: Could not find module 'chachacc.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by Kanou911** [comment]
> 仍然没有一直报错FileNotFoundError：找不到模块“chachacc.dll”（或其依赖项之一）。尝试使用带有构造函数语法的完整路径。

兄弟解决了吗，一样的报错

**Comment by Kanou911** [comment]
> > > 仍然没有一直报错FileNotFoundError：找不到模块“chachacc.dll”（或其依赖项之一）。尝试使用带有构造函数语法的完整路径。
> > 
> > 
> > 兄弟解决了吗，一样的报错
> 
> 解决不了 感觉是DLL 需要很多依赖 然后发现很多依赖DLL找不到 我PC也没有 无解

![库](https://github.com/Tontonnow/ddddhmtx/assets/54199210/3b3d9fcf-2f2c-43ac-9a7b-2bb20e058767)
我用软件查了DLL调用的库，我这缺了190多个DLL。VC的我重新安装补全了一些。不过还是差很多依赖。大概还有100来个

**Comment by 421634065** [comment]
> > > > 仍然没有一直报错FileNotFoundError：找不到模块“chachacc.dll”（或其依赖项之一）。尝试使用带有构造函数语法的完整路径。
> > > 
> > > 
> > > 兄弟解决了吗，一样的报错
> > 
> > 
> > 解决不了 感觉是DLL 需要很多依赖 然后发现很多依赖DLL找不到 我PC也没有 无解
> 
> ![库](https://private-user-images.githubusercontent.com/54199210/318427996-3b3d9fcf-2f2c-43ac-9a7b-2bb20e058767.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NzU3MTAsIm5iZiI6MTcxMTk3NTQxMCwicGF0aCI6Ii81NDE5OTIxMC8zMTg0Mjc5OTYtM2IzZDlmY2YtMmYyYy00M2FjLTlhN2ItMmJiMjBlMDU4NzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDEyNDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5YzQ4ZDU4NzczOTkxY2JlNTIyMjAxZDZiOTAxZGE5Yzc0ZDQ0MjJiOWE0NDQ0ZWQ4NzkyNDNjNWQxZTQ1YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P1eB0fxxS1QBzS3PFW_HMiQv31qAC1rMab_HOVBeQIk) 我用软件查了DLL调用的库，我这缺了190多个DLL。VC的我重新安装补全了一些。不过还是差很多依赖。大概还有100来个

我也补了不少 发些缺太多 了 好多我也找不到 就放弃了 ，只能等作者打包到DLL才行

**Comment by 421634065** [comment]
> > > > > 仍然没有一直报错FileNotFoundError：找不到模块“chachacc.dll”（或其依赖项之一）。尝试使用带有构造函数语法的完整路径。
> > > > 
> > > > 
> > > > 兄弟解决了吗，一样的报错
> > > 
> > > 
> > > 解决不了 感觉是DLL 需要很多依赖 然后发现很多依赖DLL找不到 我PC也没有 无解
> > 
> > 
> > ![库](https://private-user-images.githubusercontent.com/54199210/318427996-3b3d9fcf-2f2c-43ac-9a7b-2bb20e058767.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5ODY1NzUsIm5iZiI6MTcxMTk4NjI3NSwicGF0aCI6Ii81NDE5OTIxMC8zMTg0Mjc5OTYtM2IzZDlmY2YtMmYyYy00M2FjLTlhN2ItMmJiMjBlMDU4NzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDE1NDQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNGQ4Zjk3MWI1ZDk2ODBjYTYzOTY0NmY3Yjk3ODgxOGZlMTEyNzMxZWRhZDE5ZWY4NjMzN2U0ZWEzZGMwYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zePdD-2OU_AYkXQ0dEW6epleeGkHZNiquG_lr2MN7Y4) 我用软件查了DLL调用的库，我这缺了190多个DLL。VC的我重新安装补全了一些。不过还是差很多依赖。大概还有100来个
> 
> 不是发了cl编译的chachacl.dll，而且你这截图缺的全是系统库

是的 缺了很多 你有办法解决吗
