### ISSUE TITLE
IV只有7个字节

### ISSUE THREAD

**Issue by 421634065** [Tontonnow/ddddhmtx#2]
案例：aHR0cHM6Ly92LnFxLmNvbS94L2NvdmVyLzMyNG9sejdpbHZvMmo1Zi9mMDA0OGY5bXJseS5odG1s
IV应该是8个字节 但是获取是7位

**Comment by 421634065** [comment]
link_vid = b"f0048f9mrly"
    base = b"E7049D51AB0E67565F0C725C3C9F82D314F777E9C1634AB152BDCFB003D78C85"
    appVer = b"14.2.0.1009"
    tm = 1712586768;
    platform = 670603;
    
    获取1715AFE44D80FF18B7B8D6E090B08195,8429922

**Comment by 421634065** [comment]
感谢 ，弄好 ！！！

**Comment by 96827123** [comment]
兄弟解决环境问题了？
